# docker-compose for Grafana
version: '2'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
#    ports:
#      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=An0th3rP4ss
    restart: always
    networks:
      default:
        aliases:
          - grafana

networks:
  default:
    external:
      name: br0


volumes:
  grafana-storage:
